services:
  db:
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}/tcp
    image: postgres
    hostname: ${POSTGRES_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/db.sh:/docker-entrypoint-initdb.d/db.sh:ro
    networks:
      - app-network

  queue:
    ports:
      - 127.0.0.1:${RABBITMQ_PORT}:${RABBITMQ_PORT}
    image: rabbitmq
    hostname: ${RABBITMQ_HOST}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network

  user-ms:
    ports: 
      - 127.0.0.1:3001:3001/tcp
    depends_on:
      - db
      - queue
    build:
      args:
        APP_NAME: users
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERS_QUEUE: ${RABBITMQ_USERS_QUEUE}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  order-ms:
    ports: 
      - 127.0.0.1:3002:3002/tcp
    depends_on:
      - db
      - queue
    build:
      args:
        APP_NAME: orders
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ORDERS_DB}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERS_QUEUE: ${RABBITMQ_USERS_QUEUE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
